name: Feature Request
description: Propose a feature
labels: ["type:feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What user or system problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What should be built?
    validations:
      required: true
  - type: textarea
    id: success
    attributes:
      label: Success Criteria
    validations:
      required: true
